_core:
  default_config_hash: X6j57Vbe47rJ-RiyQeN6-6hS014CYwrnZ2dp-NVQ2_Y
admin_css: true
lazy_html: false
nojs:
  lazy: '0'
  polyfill: '0'
  classlist: '0'
  promise: '0'
  raf: '0'
  webp: '0'
fx: ''
blur_client: false
blur_storage: false
blur_minwidth: 0
noscript: false
one_pixel: true
visible_class: false
wrapper_class: false
placeholder: ''
unstyled_extensions: ''
use_encodedbox: false
use_oembed: false
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: 25
  container: ''
io:
  unblazy: false
  rootMargin: 0px
  threshold: '0'
  disconnect: false
extras: {  }
max_region_count: 0
